version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    healthcheck:
      test: curl -I --fail http://localhost/ || exit 1
      interval: 60s
      timeout: 2s
      retries: 5
    volumes:
      - ./src/:/var/www/html/
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: chall
      MYSQL_USER: secret
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql